/* drevo — C FFI Header (auto-generated by cbindgen, do not edit) */

#ifndef DREVO_H
#define DREVO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The main drevo handle.
 *
 * Created via [`Drevo::open`] (disk-backed) or
 * [`Drevo::open_in_memory`] (ephemeral). All graph operations
 * are methods on this struct.
 */
typedef struct Drevo Drevo;

/**
 * Opaque handle exposed to C consumers.
 */
typedef struct Drevo drevo_t;

/**
 * Open a disk-backed database at the given path.
 *
 * Returns an opaque handle on success, or `NULL` on failure (check
 * [`drevo_last_error`]).
 *
 * # Safety
 * `path` must be a valid NUL-terminated UTF-8 string.
 */
drevo_t *drevo_open(const char *path);

/**
 * Open an in-memory (ephemeral) database.
 *
 * Returns an opaque handle on success, or `NULL` on failure.
 *
 * # Safety
 * No preconditions — this function is always safe to call.
 */
drevo_t *drevo_open_in_memory(void);

/**
 * Close the database and free the handle.
 *
 * Returns 0 on success, -1 on failure. Passing `NULL` is an error.
 *
 * # Safety
 * `db` must be a valid handle returned by `drevo_open*`, or `NULL`.
 * After this call the handle is invalid and must not be used.
 */
int32_t drevo_close(drevo_t *db);

/**
 * Return the last error message as a C string, or `NULL` if no error.
 *
 * The caller owns the returned pointer and must free it with
 * [`drevo_free_string`].
 *
 * # Safety
 * No preconditions — this function is always safe to call.
 */
char *drevo_last_error(void);

/**
 * Free a C string previously returned by any `drevo_*` function.
 *
 * Passing `NULL` is safe (no-op).
 *
 * # Safety
 * `s` must be a pointer returned by a `drevo_*` function, or `NULL`.
 */
void drevo_free_string(char *s);

/**
 * Create a new node. Returns the created node as a JSON C string, or `NULL` on error.
 *
 * # Safety
 * All string parameters must be valid NUL-terminated UTF-8.
 * `properties_json` must be valid JSON object string.
 */
char *drevo_create_node(drevo_t *db,
                        const char *kind,
                        const char *title,
                        const char *body,
                        const char *body_html,
                        const char *properties_json);

/**
 * Get a node by ID. Returns JSON C string, or `NULL` if not found / error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_get_node(drevo_t *db, uint64_t id);

/**
 * Update a node by ID with a JSON patch. Returns updated node as JSON, or `NULL`.
 *
 * The patch JSON may contain any subset of: `title`, `kind`, `body`, `body_html`, `properties`.
 *
 * # Safety
 * `db` must be a valid handle. `patch_json` must be valid JSON.
 */
char *drevo_update_node(drevo_t *db, uint64_t id, const char *patch_json);

/**
 * Delete a node by ID. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
int32_t drevo_delete_node(drevo_t *db, uint64_t id);

/**
 * Create a new edge. Returns the created edge as JSON, or `NULL` on error.
 *
 * # Safety
 * `db` must be a valid handle. String parameters must be valid NUL-terminated UTF-8.
 */
char *drevo_create_edge(drevo_t *db,
                        uint64_t from_id,
                        uint64_t to_id,
                        const char *kind,
                        float weight,
                        const char *properties_json);

/**
 * Get an edge by ID. Returns JSON, or `NULL` if not found / error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_get_edge(drevo_t *db, uint64_t id);

/**
 * Update an edge by ID with a JSON patch. Returns updated edge as JSON, or `NULL`.
 *
 * The patch JSON may contain: `kind`, `weight`, `properties`.
 *
 * # Safety
 * `db` must be a valid handle. `patch_json` must be valid JSON.
 */
char *drevo_update_edge(drevo_t *db, uint64_t id, const char *patch_json);

/**
 * Delete an edge by ID. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
int32_t drevo_delete_edge(drevo_t *db, uint64_t id);

/**
 * Get neighbors of a node. Returns JSON array of nodes, or `NULL` on error.
 *
 * `direction`: 0 = Outgoing, 1 = Incoming, 2 = Both.
 * `edge_kind`: optional edge kind filter (pass `NULL` for no filter).
 *
 * # Safety
 * `db` must be a valid handle. `edge_kind` must be valid UTF-8 or `NULL`.
 */
char *drevo_neighbors(drevo_t *db, uint64_t node_id, int32_t direction, const char *edge_kind);

/**
 * BFS traversal from a start node. Returns JSON array of node IDs, or `NULL`.
 *
 * `direction`: 0 = Outgoing, 1 = Incoming, 2 = Both.
 * `edge_kind`: optional edge kind filter (`NULL` for no filter).
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_bfs(drevo_t *db,
                uint64_t start_id,
                uint8_t max_depth,
                int32_t direction,
                const char *edge_kind);

/**
 * DFS traversal from a start node. Returns JSON array of node IDs, or `NULL`.
 *
 * `direction`: 0 = Outgoing, 1 = Incoming, 2 = Both.
 * `edge_kind`: optional edge kind filter (`NULL` for no filter).
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_dfs(drevo_t *db,
                uint64_t start_id,
                uint8_t max_depth,
                int32_t direction,
                const char *edge_kind);

/**
 * Find the shortest path between two nodes. Returns JSON array of node IDs, or `NULL`.
 *
 * Returns `NULL` with error "no path found" if no path exists.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_shortest_path(drevo_t *db, uint64_t from_id, uint64_t to_id);

/**
 * Extract a subgraph around a root node. Returns JSON with `nodes` and `edges` arrays, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_subgraph(drevo_t *db, uint64_t root_id, uint8_t depth);

/**
 * Full-text search. Returns JSON array of `{node, score}` objects, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle. `query` must be valid NUL-terminated UTF-8.
 */
char *drevo_search_fts(drevo_t *db, const char *query, uint64_t limit);

/**
 * List nodes by kind with pagination. Returns JSON array of nodes, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle. `kind` must be valid NUL-terminated UTF-8.
 */
char *drevo_list_nodes_by_kind(drevo_t *db, const char *kind, uint64_t limit, uint64_t offset);

/**
 * List recently updated nodes. Returns JSON array of nodes, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_list_recent(drevo_t *db, uint64_t limit);

#endif  /* DREVO_H */
