/* drevo — C FFI Header (auto-generated by cbindgen, do not edit) */

#ifndef DREVO_H
#define DREVO_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Coarse capability/protocol level clients can gate on without parsing semver
 * (issue #303). Bumped when the Bolt/Cypher surface gains a
 * backwards-incompatible-to-assume capability. Surfaced by `CALL drevo.info()`.
 */
#define INFO_PROTOCOL 1

/**
 * Default `limit` applied to `GET /nodes` and `GET /edges` when the
 * client omits the query parameter. Kept in lockstep with
 * [`DEFAULT_SEARCH_LIMIT`] for predictable client behaviour across
 * endpoints.
 */
#define DEFAULT_LIST_LIMIT 50

/**
 * Maximum `limit` accepted by `GET /nodes` and `GET /edges`. Requests
 * above this cap are silently clamped so that a pathological client
 * cannot force an unbounded scan over the kind index — the same
 * rationale as [`MAX_SEARCH_LIMIT`] for the FTS endpoint.
 */
#define MAX_LIST_LIMIT 1000

/**
 * Default depth used when `GET /nodes/{id}/neighbors` omits the
 * `depth` query parameter.
 */
#define DEFAULT_NEIGHBORS_DEPTH 1

/**
 * Default depth used when `GET /nodes/{id}/subgraph` omits the
 * `depth` query parameter.
 */
#define DEFAULT_SUBGRAPH_DEPTH 1

/**
 * Default `limit` applied to `POST /search/fts` when the client omits
 * it. Matches the node/edge list defaults to keep the API consistent.
 */
#define DEFAULT_SEARCH_LIMIT 10

/**
 * Maximum `limit` accepted by `POST /search/fts`. Requests above this
 * cap are silently clamped so that a pathological client cannot force
 * a huge scoring pass.
 */
#define MAX_SEARCH_LIMIT 1000

/**
 * Default number of keywords extracted per node for faceting.
 */
#define DEFAULT_FACET_KEYWORDS 5

/**
 * Upper bound on the per-node keyword count for faceting.
 */
#define MAX_FACET_KEYWORDS 50

/**
 * Maximum bytes carried in a single chunk (the 16-bit length field's
 * max value). Messages longer than this are split across multiple
 * chunks.
 */
#define MAX_CHUNK_SIZE (uintptr_t)UINT16_MAX

/**
 * Total length of the client handshake message in bytes.
 */
#define HANDSHAKE_LEN 20

/**
 * `HELLO` request: connection setup.
 */
#define HELLO 1

/**
 * `GOODBYE` request: close the session.
 */
#define GOODBYE 2

/**
 * `RESET` request: clear failed state / drop pending stream.
 */
#define RESET 15

/**
 * `RUN` request: parse + execute a Cypher query.
 */
#define RUN 16

/**
 * `BEGIN` request: open an explicit transaction (Phase 11 task `00072`).
 */
#define BEGIN 17

/**
 * `COMMIT` request: commit the open explicit transaction (Phase 11 task `00072`).
 */
#define COMMIT 18

/**
 * `ROLLBACK` request: roll back the open explicit transaction (Phase 11 task `00072`).
 */
#define ROLLBACK 19

/**
 * `DISCARD` request: drop pending rows without emitting them.
 */
#define DISCARD 47

/**
 * `PULL` request: stream pending rows as `RECORD` messages.
 */
#define PULL 63

/**
 * `SUCCESS` response.
 */
#define SUCCESS 112

/**
 * `RECORD` response: a single row from a streaming result set.
 */
#define RECORD 113

/**
 * `IGNORED` response: returned for messages received while in `Failed`.
 */
#define IGNORED 126

/**
 * `FAILURE` response.
 */
#define FAILURE 127

/**
 * Maximum database-name length in bytes. Comfortably below any filesystem
 * component limit once the `.redb` suffix is added.
 */
#define MAX_NAME_LEN 64

/**
 * Default trigram-set Jaccard threshold for [`FacetCollapse::Lexical`].
 *
 * `0.34` means two keywords merge on the trigram signal when about a third
 * of their combined trigrams are shared — loose enough to fold a
 * single-edit / transposition typo (e.g. *databse* ↔ *database*, Jaccard
 * ≈ 0.38), tight enough that words sharing only a common prefix stay apart
 * (*anxiety* ↔ *anxious*, Jaccard ≈ 0.2 — a synonym-ish pair that is the
 * *semantic* axis's job, not the lexical one). Stemming (always applied in
 * lexical mode) handles the morphological families regardless of this
 * value.
 */
#define DEFAULT_TRIGRAM_THRESHOLD 0.34

/**
 * Default cosine threshold for [`FacetCollapse::Semantic`].
 *
 * `0.85` is a conservative synonym cutoff for unit-normalized sentence /
 * word embeddings; lower it to merge more aggressively.
 */
#define DEFAULT_COSINE_THRESHOLD 0.85

/**
 * A coarse default for the in-memory width of one result row, in bytes, used
 * when a caller has no better figure. One of the planner's documented
 * `DEFAULT_*` magic numbers (see [`crate::planner::cardinality`]): a handful
 * of bound values — node ids, short property scalars — at a conservative
 * ~64 bytes each. Callers that know their projection width should pass it
 * directly to [`estimate_peak_memory`] / [`MemoryBudget::admits`].
 */
#define DEFAULT_ROW_WIDTH_BYTES 64

/**
 * Default fraction of rows passing an equality predicate (`n.p = v`) when the
 * catalogue holds no distinct-value count for the property.
 */
#define DEFAULT_EQUALITY_SELECTIVITY 0.1

/**
 * Default fraction of rows passing a range predicate (`<`, `<=`, `>`, `>=`).
 */
#define DEFAULT_RANGE_SELECTIVITY (1.0 / 3.0)

/**
 * Default fraction of rows passing a string-match predicate (`STARTS WITH`,
 * `ENDS WITH`, `CONTAINS`, `=~`).
 */
#define DEFAULT_STRING_MATCH_SELECTIVITY 0.1

/**
 * Default fraction of rows passing an `IS NULL` predicate (most properties
 * are present, so a null match is rare).
 */
#define DEFAULT_NULL_SELECTIVITY 0.1

/**
 * Fallback fraction for any predicate shape the estimator does not model
 * (an opaque function call, a property-to-property comparison, …).
 */
#define DEFAULT_PREDICATE_SELECTIVITY 0.25

/**
 * Multiple of the average degree at or above which a node is treated as a
 * **supernode** when no explicit threshold is configured (task `00087`).
 *
 * On real graphs the degree distribution is heavily skewed: a handful of
 * "hub" nodes (a popular tag, a prolific author, a shared dependency) carry
 * orders of magnitude more edges than the average. Driving a traversal *out
 * of* such a node fans out across its entire degree, so the planner needs to
 * recognise one. A node whose degree is this many times the graph average is
 * considered a supernode.
 */
#define DEFAULT_SUPERNODE_THRESHOLD_FACTOR 100.0

/**
 * Floor for the derived supernode threshold, so that on small or sparse graphs
 * — where the average degree is tiny — an ordinary, well-connected node is not
 * mistaken for a supernode (task `00087`).
 */
#define MIN_SUPERNODE_THRESHOLD 100

/**
 * Current on-disk format **major** version this build writes and reads.
 *
 * Compatibility rule (semver-style): a build opens any file whose major
 * version is `<= FORMAT_MAJOR`. A file with a greater major was written by
 * a newer, layout-incompatible drevo and is refused with
 * [`StorageError::IncompatibleFormat`] instead of being silently misread.
 * Files predating format versioning carry no marker and are treated as the
 * original `1.0` format (then stamped on first open). This is the on-disk
 * durability guarantee for the agent-memory-graph file (issue #48).
 *
 * **v2** (#243 slice 2): the adjacency index moved to the kind-in-key layout
 * `out:{from}:{kind}:{edge}`. A v1 file opens (its major `1 <= 2`), but the
 * graph layer detects the old adjacency layout and refuses it with
 * [`crate::error::DrevoError::NeedsMigration`] until
 * [`crate::db::Drevo::migrate_adjacency`] rewrites the index and re-stamps.
 */
#define FORMAT_MAJOR 2

/**
 * Current on-disk format **minor** version. Bumped for additive,
 * backward-compatible layout changes within a major; purely informational
 * for the compatibility check (any minor of a compatible major opens).
 */
#define FORMAT_MINOR 0

/**
 * The default batch size used by [`IngestConsumer::new`] when none is
 * specified.
 */
#define IngestConsumer_DEFAULT_BATCH_SIZE 256

/**
 * A negotiated Bolt protocol version: `major.minor`. Wire format is
 * `[0x00, 0x00, minor, major]` per the Bolt v4 spec.
 */
typedef struct BoltVersion BoltVersion;

/**
 * The main drevo handle.
 *
 * Created via `Drevo::open` (disk-backed, requires the
 * `redb-backend` Cargo feature) or [`Drevo::open_in_memory`]
 * (ephemeral). All graph operations are methods on this struct.
 */
typedef struct Drevo Drevo;

/**
 * A log sequence number — a strictly increasing identifier stamped on every
 * [`WalRecord`].
 *
 * [`Lsn::ZERO`] is the sentinel for "no record yet": a freshly created log
 * has [`WriteAheadLog::last_lsn`] equal to `ZERO`, and a freshly created
 * replica has applied up to `ZERO`. The first appended record is
 * [`Lsn`]`(1)`.
 */
typedef struct Lsn Lsn;

/**
 * Opaque handle exposed to C consumers.
 */
typedef struct Drevo drevo_t;

/**
 * A monotonically increasing transaction identifier.
 *
 * Real transactions start at `1`; [`INVALID_XID`] (`0`) is reserved as a
 * sentinel meaning "no transaction" — it is the `xmax` of a live tuple
 * version (one that has never been deleted) and is never handed out by
 * [`TransactionManager::begin`].
 */
typedef uint64_t Xid;



/**
 * The reserved sentinel transaction id (`0`).
 *
 * Used as the `xmax` of a version that is still live and as the "no owner"
 * marker. [`TransactionManager::begin`] always returns a value `>= 1`, so a
 * real transaction can never collide with it.
 */
#define INVALID_XID 0



/**
 * Open a disk-backed database at the given path.
 *
 * Returns an opaque handle on success, or `NULL` on failure (check
 * [`drevo_last_error`]).
 *
 * # Safety
 * `path` must be a valid NUL-terminated UTF-8 string.
 */
drevo_t *drevo_open(const char *path);

/**
 * Open an in-memory (ephemeral) database.
 *
 * Returns an opaque handle on success, or `NULL` on failure.
 *
 * # Safety
 * No preconditions — this function is always safe to call.
 */
drevo_t *drevo_open_in_memory(void);

/**
 * Close the database and free the handle.
 *
 * Returns 0 on success, -1 on failure. Passing `NULL` is an error.
 *
 * # Safety
 * `db` must be a valid handle returned by `drevo_open*`, or `NULL`.
 * After this call the handle is invalid and must not be used.
 * Calling this function twice on the same pointer is undefined behavior
 * (see the module-level "Lifecycle and double-free" docs).
 */
int32_t drevo_close(drevo_t *db);

/**
 * Return the last error message as a C string, or `NULL` if no error.
 *
 * The caller owns the returned pointer and must free it with
 * [`drevo_free_string`].
 *
 * # Safety
 * No preconditions — this function is always safe to call.
 */
char *drevo_last_error(void);

/**
 * Free a C string previously returned by any `drevo_*` function.
 *
 * Passing `NULL` is safe (no-op).
 *
 * # Safety
 * `s` must be a pointer returned by a `drevo_*` function, or `NULL`.
 */
void drevo_free_string(char *s);

/**
 * Create a new node. Returns the created node as a JSON C string, or `NULL` on error.
 *
 * # Safety
 * All string parameters must be valid NUL-terminated UTF-8.
 * `properties_json` must be valid JSON object string.
 */
char *drevo_create_node(drevo_t *db,
                        const char *kind,
                        const char *title,
                        const char *body,
                        const char *body_html,
                        const char *properties_json);

/**
 * Get a node by ID. Returns JSON C string, or `NULL` if not found / error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_get_node(drevo_t *db, uint64_t id);

/**
 * Update a node by ID with a JSON patch. Returns updated node as JSON, or `NULL`.
 *
 * The patch JSON may contain any subset of: `title`, `kind`, `body`, `body_html`, `properties`.
 *
 * # Safety
 * `db` must be a valid handle. `patch_json` must be valid JSON.
 */
char *drevo_update_node(drevo_t *db, uint64_t id, const char *patch_json);

/**
 * Delete a node by ID. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
int32_t drevo_delete_node(drevo_t *db, uint64_t id);

/**
 * Create a new edge. Returns the created edge as JSON, or `NULL` on error.
 *
 * # Safety
 * `db` must be a valid handle. String parameters must be valid NUL-terminated UTF-8.
 */
char *drevo_create_edge(drevo_t *db,
                        uint64_t from_id,
                        uint64_t to_id,
                        const char *kind,
                        float weight,
                        const char *properties_json);

/**
 * Get an edge by ID. Returns JSON, or `NULL` if not found / error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_get_edge(drevo_t *db, uint64_t id);

/**
 * Update an edge by ID with a JSON patch. Returns updated edge as JSON, or `NULL`.
 *
 * The patch JSON may contain: `kind`, `weight`, `properties`.
 *
 * # Safety
 * `db` must be a valid handle. `patch_json` must be valid JSON.
 */
char *drevo_update_edge(drevo_t *db, uint64_t id, const char *patch_json);

/**
 * Delete an edge by ID. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `db` must be a valid handle.
 */
int32_t drevo_delete_edge(drevo_t *db, uint64_t id);

/**
 * Get neighbors of a node. Returns JSON array of nodes, or `NULL` on error.
 *
 * `direction`: 0 = Outgoing, 1 = Incoming, 2 = Both.
 * `edge_kind`: optional edge kind filter (pass `NULL` for no filter).
 *
 * # Safety
 * `db` must be a valid handle. `edge_kind` must be valid UTF-8 or `NULL`.
 */
char *drevo_neighbors(drevo_t *db, uint64_t node_id, int32_t direction, const char *edge_kind);

/**
 * BFS traversal from a start node. Returns JSON array of node IDs, or `NULL`.
 *
 * `direction`: 0 = Outgoing, 1 = Incoming, 2 = Both.
 * `edge_kind`: optional edge kind filter (`NULL` for no filter).
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_bfs(drevo_t *db,
                uint64_t start_id,
                uint8_t max_depth,
                int32_t direction,
                const char *edge_kind);

/**
 * DFS traversal from a start node. Returns JSON array of node IDs, or `NULL`.
 *
 * `direction`: 0 = Outgoing, 1 = Incoming, 2 = Both.
 * `edge_kind`: optional edge kind filter (`NULL` for no filter).
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_dfs(drevo_t *db,
                uint64_t start_id,
                uint8_t max_depth,
                int32_t direction,
                const char *edge_kind);

/**
 * Find the shortest path between two nodes. Returns JSON array of node IDs, or `NULL`.
 *
 * Returns `NULL` with error "no path found" if no path exists.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_shortest_path(drevo_t *db, uint64_t from_id, uint64_t to_id);

/**
 * Extract a subgraph around a root node. Returns JSON with `nodes` and `edges` arrays, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_subgraph(drevo_t *db, uint64_t root_id, uint8_t depth);

/**
 * Full-text search. Returns JSON array of `{node, score}` objects, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle. `query` must be valid NUL-terminated UTF-8.
 */
char *drevo_search_fts(drevo_t *db, const char *query, uint64_t limit);

/**
 * List nodes by kind with pagination. Returns JSON array of nodes, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle. `kind` must be valid NUL-terminated UTF-8.
 */
char *drevo_list_nodes_by_kind(drevo_t *db, const char *kind, uint64_t limit, uint64_t offset);

/**
 * List recently updated nodes. Returns JSON array of nodes, or `NULL`.
 *
 * # Safety
 * `db` must be a valid handle.
 */
char *drevo_list_recent(drevo_t *db, uint64_t limit);

#endif  /* DREVO_H */
