#!/usr/bin/env bash
# Regenerate src/grpc/drevo.v1.rs from proto/drevo.proto (issue #583).
#
# The generated code is checked in so a `grpc` build needs neither protoc nor
# a build script. This script builds a throwaway generator with the same
# tonic-build version drevo's tonic uses and a vendored protoc, then writes
# the file with a CRC-32 of the .proto in its header; the
# `generated_code_matches_the_proto` test fails when the two drift apart.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/src"
cat > "$work/Cargo.toml" <<'TOML'
[package]
name = "drevo-grpc-gen"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
tonic-build = "=0.13.1"
protoc-bin-vendored = "3"
TOML
cat > "$work/src/main.rs" <<'RS'
fn main() {
    let args: Vec<String> = std::env::args().collect();
    let (proto, out) = (&args[1], &args[2]);
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("vendored protoc");
    std::env::set_var("PROTOC", protoc);
    let dir = std::path::Path::new(proto).parent().expect("proto dir");
    tonic_build::configure()
        .out_dir(out)
        .compile_protos(&[proto], &[dir])
        .expect("compile protos");
}
RS
cargo run --quiet --manifest-path "$work/Cargo.toml" -- "$root/proto/drevo.proto" "$work"
crc="$(python3 -c "import zlib,sys; print('%08x' % (zlib.crc32(open(sys.argv[1],'rb').read()) & 0xffffffff))" "$root/proto/drevo.proto")"
{
  echo "// @generated by scripts/gen-grpc.sh from proto/drevo.proto — do not edit."
  echo "// proto-crc32: $crc"
  cat "$work/drevo.v1.rs"
} > "$root/src/grpc/drevo.v1.rs"
echo "wrote src/grpc/drevo.v1.rs (proto-crc32 $crc)"
