//! Hybrid Logical Clock (HLC) — causal versioning primitive for multi-writer
//! convergence (issue #389, primitive #1).
//!
//! drevo stamps writes with a wall clock ([`crate::model::now_ms`]) and a
//! UUID v7. Wall clocks cannot safely order **concurrent** edits made on
//! different peers: clock skew means "later timestamp" need not mean "happened
//! after". A [Hybrid Logical Clock](https://cse.buffalo.edu/tech-reports/2014-04.pdf)
//! (Kulkarni et al., 2014) fixes this: it tracks physical time when it can, but
//! guarantees a **monotonic, causally consistent** timestamp regardless of how
//! the physical clock jumps, so `(hlc, origin_id)` gives a total, deterministic
//! ordering key for merge.
//!
//! This module is the pure primitive: the [`Hlc`](crate::hlc::Hlc) timestamp
//! and the [`HlcClock`](crate::hlc::HlcClock) that generates and advances it.
//! Wiring it into the write path / on-disk format, per-property LWW merge, and
//! tombstones are the follow-up slices of #389. Dependency-free, infallible,
//! always compiled, WASM-safe.
//!
//! # Determinism for tests
//!
//! The core steps — [`tick`](crate::hlc::HlcClock::tick) and
//! [`update`](crate::hlc::HlcClock::update) — take the physical time in
//! milliseconds as an argument, so tests drive them with a virtual clock
//! (including one that runs **backwards**). [`now`](crate::hlc::HlcClock::now) /
//! [`observe`](crate::hlc::HlcClock::observe) are the production entry points
//! that read the real wall clock.

use serde::{Deserialize, Serialize};

/// A Hybrid Logical Clock timestamp: a physical-time component in Unix
/// milliseconds plus a logical counter that breaks ties within the same
/// millisecond.
///
/// Ordering is lexicographic — `wall_ms` first, then `counter` — which the
/// derived [`Ord`] gives directly (the fields are declared in that order). Two
/// timestamps generated by one clock are always strictly ordered; timestamps
/// from different peers are made total by pairing the `Hlc` with an `origin_id`
/// (a later slice), so equal `Hlc` values tie-break on the origin.
///
/// [`Hlc::default`] is `(0, 0)`, the minimum — a sensible "before any write"
/// zero value.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default, Serialize, Deserialize,
)]
pub struct Hlc {
    /// Physical-time component, Unix milliseconds (may be negative only if the
    /// host clock is set before the Unix epoch — see [`crate::model::now_ms`]).
    wall_ms: i64,
    /// Logical counter distinguishing events within the same `wall_ms`.
    counter: u32,
}

impl Hlc {
    /// Construct a timestamp from its parts. Mostly for tests and
    /// deserialization from an existing store; production code obtains
    /// timestamps from an [`HlcClock`].
    #[must_use]
    pub fn new(wall_ms: i64, counter: u32) -> Self {
        Self { wall_ms, counter }
    }

    /// The physical-time component (Unix milliseconds).
    #[must_use]
    pub fn wall_ms(&self) -> i64 {
        self.wall_ms
    }

    /// The logical counter within [`Self::wall_ms`].
    #[must_use]
    pub fn counter(&self) -> u32 {
        self.counter
    }

    /// The successor within the same wall time, rolling the wall forward by one
    /// millisecond if the counter would overflow `u32`. Keeps strict
    /// monotonicity even in the pathological case of `u32::MAX` events in a
    /// single millisecond.
    fn bump_same_wall(wall_ms: i64, base_counter: u32) -> Self {
        match base_counter.checked_add(1) {
            Some(counter) => Self { wall_ms, counter },
            None => Self {
                wall_ms: wall_ms.saturating_add(1),
                counter: 0,
            },
        }
    }
}

impl std::fmt::Display for Hlc {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}.{}", self.wall_ms, self.counter)
    }
}

/// A Hybrid Logical Clock generator, owning the last timestamp it issued.
///
/// Not internally synchronised: a shared clock (e.g. one per database) is
/// wrapped in a `Mutex` by the caller. Every method returns the freshly issued
/// timestamp, which is always strictly greater than the previous one, so a
/// sequence of local events is totally ordered even when the physical clock
/// stalls or runs backwards.
#[derive(Debug, Clone)]
pub struct HlcClock {
    last: Hlc,
}

impl Default for HlcClock {
    fn default() -> Self {
        Self::new()
    }
}

impl HlcClock {
    /// A fresh clock whose last timestamp is the zero value `(0, 0)`.
    #[must_use]
    pub fn new() -> Self {
        Self {
            last: Hlc::default(),
        }
    }

    /// Resume a clock from a persisted last timestamp (e.g. the maximum `Hlc`
    /// recovered from the store on boot), so newly issued timestamps continue
    /// to strictly increase across restarts.
    #[must_use]
    pub fn from_last(last: Hlc) -> Self {
        Self { last }
    }

    /// The last timestamp issued (the clock's current high-water mark).
    #[must_use]
    pub fn last(&self) -> Hlc {
        self.last
    }

    /// Advance the clock for a **local** event at physical time `physical_ms`
    /// and return the new timestamp.
    ///
    /// If physical time has moved past the last wall component the counter
    /// resets to `0`; otherwise (physical time equal or *behind*, e.g. clock
    /// skew) the wall component is held and the counter increments — so the
    /// result is always strictly greater than [`Self::last`].
    pub fn tick(&mut self, physical_ms: i64) -> Hlc {
        let prev = self.last;
        let wall = prev.wall_ms.max(physical_ms);
        self.last = if wall == prev.wall_ms {
            Hlc::bump_same_wall(wall, prev.counter)
        } else {
            Hlc::new(wall, 0)
        };
        self.last
    }

    /// Advance the clock on **receiving** a remote timestamp `remote` at
    /// physical time `physical_ms`, and return the new local timestamp.
    ///
    /// The wall component becomes the maximum of the local last, the remote,
    /// and physical time; the counter is derived so the result is strictly
    /// greater than both [`Self::last`] and `remote` — establishing the causal
    /// "happens-after" relationship a merge relies on.
    pub fn update(&mut self, remote: Hlc, physical_ms: i64) -> Hlc {
        let prev = self.last;
        let wall = prev.wall_ms.max(remote.wall_ms).max(physical_ms);
        self.last = if wall == prev.wall_ms && wall == remote.wall_ms {
            Hlc::bump_same_wall(wall, prev.counter.max(remote.counter))
        } else if wall == prev.wall_ms {
            Hlc::bump_same_wall(wall, prev.counter)
        } else if wall == remote.wall_ms {
            Hlc::bump_same_wall(wall, remote.counter)
        } else {
            Hlc::new(wall, 0)
        };
        self.last
    }

    /// Advance for a local event using the real wall clock
    /// ([`crate::model::now_ms`]). The production counterpart of [`Self::tick`].
    pub fn now(&mut self) -> Hlc {
        self.tick(crate::model::now_ms())
    }

    /// Advance on receiving `remote` using the real wall clock. The production
    /// counterpart of [`Self::update`].
    pub fn observe(&mut self, remote: Hlc) -> Hlc {
        self.update(remote, crate::model::now_ms())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_is_the_minimum() {
        assert_eq!(Hlc::default(), Hlc::new(0, 0));
        assert!(Hlc::default() < Hlc::new(0, 1));
        assert!(Hlc::default() < Hlc::new(1, 0));
    }

    #[test]
    fn ordering_is_wall_then_counter() {
        assert!(Hlc::new(5, 9) < Hlc::new(6, 0)); // wall dominates
        assert!(Hlc::new(5, 1) < Hlc::new(5, 2)); // counter breaks ties
        assert_eq!(Hlc::new(5, 2), Hlc::new(5, 2));
    }

    #[test]
    fn tick_resets_counter_when_wall_advances() {
        let mut c = HlcClock::new();
        let a = c.tick(100);
        assert_eq!(a, Hlc::new(100, 0));
        let b = c.tick(101);
        assert_eq!(b, Hlc::new(101, 0));
    }

    #[test]
    fn tick_increments_counter_within_same_millisecond() {
        let mut c = HlcClock::new();
        assert_eq!(c.tick(100), Hlc::new(100, 0));
        assert_eq!(c.tick(100), Hlc::new(100, 1));
        assert_eq!(c.tick(100), Hlc::new(100, 2));
    }

    #[test]
    fn tick_is_monotonic_when_the_clock_runs_backwards() {
        let mut c = HlcClock::new();
        let a = c.tick(1_000);
        // Physical clock jumps back by 500ms — the HLC must not regress.
        let b = c.tick(500);
        let d = c.tick(499);
        assert!(a < b, "{a} !< {b}");
        assert!(b < d, "{b} !< {d}");
        // Wall stays pinned at the high-water mark, counter carries the order.
        assert_eq!(b, Hlc::new(1_000, 1));
        assert_eq!(d, Hlc::new(1_000, 2));
    }

    #[test]
    fn tick_is_strictly_increasing_over_many_events() {
        let mut c = HlcClock::new();
        let mut prev = c.last();
        // Mix of forward, stalled, and backward physical times.
        for pt in [1, 1, 1, 2, 2, 1, 5, 3, 5, 5, 4] {
            let next = c.tick(pt);
            assert!(next > prev, "not increasing: {prev} then {next}");
            prev = next;
        }
    }

    #[test]
    fn update_takes_the_max_and_advances_past_both() {
        let mut c = HlcClock::from_last(Hlc::new(10, 3));
        let remote = Hlc::new(10, 7);
        // Same wall on both sides + physical behind → max(counter)+1.
        let got = c.update(remote, 5);
        assert_eq!(got, Hlc::new(10, 8));
        assert!(got > Hlc::new(10, 3));
        assert!(got > remote);
    }

    #[test]
    fn update_from_a_future_remote_adopts_its_wall() {
        let mut c = HlcClock::from_last(Hlc::new(10, 0));
        // Remote is ahead in wall time; local physical clock is behind.
        let got = c.update(Hlc::new(50, 4), 12);
        assert_eq!(got, Hlc::new(50, 5), "adopt remote wall, counter+1");
        assert!(got > Hlc::new(10, 0));
        assert!(got > Hlc::new(50, 4));
    }

    #[test]
    fn update_prefers_physical_time_when_it_leads() {
        let mut c = HlcClock::from_last(Hlc::new(10, 9));
        // Physical time is ahead of both local and remote → fresh counter.
        let got = c.update(Hlc::new(20, 2), 100);
        assert_eq!(got, Hlc::new(100, 0));
    }

    #[test]
    fn counter_overflow_rolls_the_wall_forward() {
        let mut c = HlcClock::from_last(Hlc::new(10, u32::MAX));
        // Another event in the same millisecond would overflow the counter;
        // the wall rolls forward by 1ms and the counter resets, staying
        // strictly greater.
        let got = c.tick(10);
        assert_eq!(got, Hlc::new(11, 0));
        assert!(got > Hlc::new(10, u32::MAX));
    }

    #[test]
    fn serde_round_trips() {
        let ts = Hlc::new(1_726_000_000_123, 42);
        let json = serde_json::to_string(&ts).unwrap();
        let back: Hlc = serde_json::from_str(&json).unwrap();
        assert_eq!(ts, back);
    }

    #[test]
    fn display_is_wall_dot_counter() {
        assert_eq!(Hlc::new(123, 4).to_string(), "123.4");
    }

    #[test]
    fn now_and_observe_advance_using_the_real_clock() {
        let mut c = HlcClock::new();
        let a = c.now();
        let b = c.now();
        assert!(b > a, "real-clock now() must be monotonic");
        // Observing a far-future remote adopts its wall and still advances.
        let future = Hlc::new(a.wall_ms() + 1_000_000, 0);
        let d = c.observe(future);
        assert!(d > future);
        assert!(d > b);
    }
}
